### ISSUE TITLE
Losing Dragons

### ISSUE THREAD

**Issue by lnevo** [mbb10324/MountUp#1]
I keep running into a situation where my macro isn't working and when I manually try /MountUpDragon it says there were no dragon riding mounts found. A /reload solves the problem. Other mounts typically work.

**Comment by lnevo** [comment]
Here's the error I get: 
No usable dragon riding mounts found in your collection.
No usable flying mounts found in your collection.
No usable ground mounts found in your collection. 

Surprisingly, my "repair" mount - Using Fav works ok :)

Here's the bugsack:
96x MountUp/MountUp.lua:82: bad argument #1 to 'random' (interval is empty)
[string "=[C]"]: in function `random'
[string "@MountUp/MountUp.lua"]:82: in function `?'
[string "@FrameXML/ChatFrame.lua"]:5291: in function <FrameXML/ChatFrame.lua:5237>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4948: in function `ChatEdit_SendText'
[string "@MacroTalk/MacroTalk.lua"]:24: in function `MacroTalk_DoCommand'
[string "@MacroTalk/MacroTalkCommands.lua"]:200: in function `?'
[string "@FrameXML/ChatFrame.lua"]:5291: in function <FrameXML/ChatFrame.lua:5237>[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4948: in function `ChatEdit_SendText'
...
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function <FrameXML/SecureTemplates.lua:730>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:266: in function <FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:296: in function <FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals:
(*temporary) = 0

**Comment by mbb10324** [comment]
Thanks for the feedback, and providing an error message, this will help a lot in solving the problem! Does this only occur when trying the `/MountUpDragon`, or have you also experienced this with other macro commands provided by the addon?

**Comment by mbb10324** [comment]
I was able to replicate the issue once, and believe I found the root of the issue. since the issue is intermittent, I'm going to spend a day testing to ensure the problem does not arise again, then I will push a release update that fixes it. Thanks for pointing this out!

**Comment by lnevo** [comment]
Awesome. I'll be raiding tonight so no worries :) It did happen with other commands, you can see the outputs in the example, but I notice it mostly on the Dragon one. Hopefully you got it. Looking forward to testing as well!

**Comment by mbb10324** [comment]
A release update should hit the curse forge app shortly (v1.0.5) that fixes this. I spent a day testing and did not get the error again, if you have any other issues or feedback feel free to reach out!

**Comment by lnevo** [comment]
Still having the problem, definitely related to zoning.
